import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "GPT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
      <div className="flex">

<div className="bg-black text-gray-200 max-w-[250px] h-screen overflow-y-auto md:min-w-[220px]">
  <Sidebar/>
</div>
<div className="bg-[#212121] flex-1 h-screen overflow-hidden relative text-gray-200">
<Header/>
{children}
</div>
</div>
      </SessionProvider>
      <Toaster position="top-right" toastOptions={{style:{backgroundColor:"black",color:"white"}}}/>

      </body>
    </html>
  );
}
